name: Deploy to OCI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        # ssh host
        host: ${{ secrets.OCI_VM_IP }}
        username: ${{ secrets.OCI_VM_USERNAME }}
        key: ${{ secrets.OCI_VM_SSH }}
        # execute commands
        script: |
          cd ~/matheditor-llama
          git fetch
          git reset --hard origin/main
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate
          sudo systemctl restart matheditor-llama